name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 15m
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            cd ~/home/project/porto/porto-app
            git pull origin main
            git status
            sudo npm install pm2@latest -g
            sudo npm install -g pnpm
            sudo pnpm i --production=false
            sudo pnpm run build
            sudo pm2 start .output/server/index.mjs --name "porto-app"
